### PR TITLE
fix(node)!: Do not fail on dns-over-https

### LINKED ISSUE #632: bug: lumina NodeBuilder fails to start if one of the DNS of the Bootstrappers cannot be resolved
```
NodeBuilder: Could not resolve bootnode addresses: Could not parse response: Failed deserializing DoH response: Error: missing field `Answer`
```

Instead of failing at the start of the node, if only one of the DNS fails to resolve, the node should try all Bootnodes and use the one where the IP is available and the node can connect to.

### PR DESCRIPTION
**Pull request by oblique**
Fixes #632

### CODE REVIEW

File: node/src/utils/dns.rs [hunk 1]
```diff
@@ -20,17 +21,17 @@ pub(crate) enum Error {
...
-) -> Result<Vec<Multiaddr>, Error> {
+pub(crate) async fn resolve_bootnode_addresses(addrs: Vec<Multiaddr>) -> Vec<Multiaddr> {
     let mut bootnodes = Vec::with_capacity(addrs.len());
 
     for addr in addrs {
-        let resolved_addrs = resolve_dnsaddr_multiaddress(addr, DEFAULT_DNS_ADDR).await?;
-        bootnodes.extend(resolved_addrs.into_iter());
+        match resolve_dnsaddr_multiaddress(&addr, DEFAULT_DNS_ADDR).await {
+            Ok(resolved_addrs) => bootnodes.extend(resolved_addrs.into_iter()),
+            Err(e) => error!("Failed to resolve {addr}: {e}"),
```
Comment (zvolin) [inline node/src/utils/dns.rs]: let's make it a warning

**Review by zvolin — APPROVED** [review]

File: node/src/utils/dns.rs (hunk 1 above)
Comment (oblique) [reply node/src/utils/dns.rs]: done
